<?php

namespace Database\Seeders;

use App\Models\Categorie;
use App\Models\Fournisseur;
use App\Models\Produit;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    public function run(): void
    {
        $cats = Categorie::pluck('id', 'nom');

        $fournisseurs = Fournisseur::pluck('id', 'nom');
        $lafarge  = $fournisseurs['Lafarge Holcim Maroc'] ?? null;
        $sonasid  = $fournisseurs['Sonasid Acier'] ?? null;
        $tileya   = $fournisseurs['Tileya Carrelage'] ?? null;
        $plomberie= $fournisseurs['Société Marocaine de Plomberie'] ?? null;
        $colorplus= $fournisseurs['ColorPlus Peintures'] ?? null;
        $boisCo   = $fournisseurs['Bois & Co Maroc'] ?? null;
        $electro  = $fournisseurs['Electro BTP Supply'] ?? null;
        $iso      = $fournisseurs['Isomaroc Isolation'] ?? null;

        $produits = [
            // ── Ciment & Béton ──────────────────────────────────────────────
            [
                'reference'    => 'CIM-CPJ-001',
                'designation'  => 'Ciment CPJ 45 – Sac 50 kg',
                'description'  => 'Ciment Portland avec Calcaire de classe 45. Idéal pour maçonnerie et enduits.',
                'prix_achat'   => 52.00,
                'prix_vente_ht'=> 68.00,
                'tva'          => 20,
                'unite'        => 'sac',
                'stock_actuel' => 480,
                'stock_minimum'=> 100,
                'stock_maximum'=> 1000,
                'categorie_id' => $cats['Ciment CPJ'] ?? $cats['Ciment & Béton'],
                'fournisseur_id'=> $lafarge,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'CIM-CPA-001',
                'designation'  => 'Ciment CPA 55 – Sac 50 kg',
                'description'  => 'Ciment Portland Artificiel haute résistance. Usage structure et béton armé.',
                'prix_achat'   => 58.00,
                'prix_vente_ht'=> 75.00,
                'tva'          => 20,
                'unite'        => 'sac',
                'stock_actuel' => 320,
                'stock_minimum'=> 80,
                'stock_maximum'=> 800,
                'categorie_id' => $cats['Ciment CPA'] ?? $cats['Ciment & Béton'],
                'fournisseur_id'=> $lafarge,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'CIM-PRET-001',
                'designation'  => 'Béton prêt à l\'emploi B25 – m³',
                'description'  => 'Béton dosé à 350 kg/m³. Livraison par camion toupie.',
                'prix_achat'   => 850.00,
                'prix_vente_ht'=> 1100.00,
                'tva'          => 20,
                'unite'        => 'm³',
                'stock_actuel' => 50,
                'stock_minimum'=> 10,
                'stock_maximum'=> 200,
                'categorie_id' => $cats['Béton prêt à l\'emploi'] ?? $cats['Ciment & Béton'],
                'fournisseur_id'=> $lafarge,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'CIM-BLK-001',
                'designation'  => 'Bloc béton creux 20×20×40',
                'description'  => 'Parpaing creux standard pour construction de murs.',
                'prix_achat'   => 4.20,
                'prix_vente_ht'=> 5.80,
                'tva'          => 20,
                'unite'        => 'unité',
                'stock_actuel' => 3500,
                'stock_minimum'=> 500,
                'stock_maximum'=> 10000,
                'categorie_id' => $cats['Ciment & Béton'],
                'fournisseur_id'=> $lafarge,
                'statut'       => 'actif',
            ],

            // ── Fer & Acier ─────────────────────────────────────────────────
            [
                'reference'    => 'FER-HA-010',
                'designation'  => 'Rond à béton HA10 – 12 mètres',
                'description'  => 'Acier haute adhérence diamètre 10 mm. Barre de 12 mètres.',
                'prix_achat'   => 45.00,
                'prix_vente_ht'=> 58.00,
                'tva'          => 20,
                'unite'        => 'barre',
                'stock_actuel' => 280,
                'stock_minimum'=> 50,
                'stock_maximum'=> 600,
                'categorie_id' => $cats['Ronds à béton'] ?? $cats['Fer & Acier'],
                'fournisseur_id'=> $sonasid,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'FER-HA-012',
                'designation'  => 'Rond à béton HA12 – 12 mètres',
                'description'  => 'Acier haute adhérence diamètre 12 mm. Barre de 12 mètres.',
                'prix_achat'   => 62.00,
                'prix_vente_ht'=> 79.00,
                'tva'          => 20,
                'unite'        => 'barre',
                'stock_actuel' => 195,
                'stock_minimum'=> 40,
                'stock_maximum'=> 500,
                'categorie_id' => $cats['Ronds à béton'] ?? $cats['Fer & Acier'],
                'fournisseur_id'=> $sonasid,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'FER-HA-016',
                'designation'  => 'Rond à béton HA16 – 12 mètres',
                'description'  => 'Acier haute adhérence diamètre 16 mm. Barre de 12 mètres.',
                'prix_achat'   => 108.00,
                'prix_vente_ht'=> 138.00,
                'tva'          => 20,
                'unite'        => 'barre',
                'stock_actuel' => 90,
                'stock_minimum'=> 20,
                'stock_maximum'=> 300,
                'categorie_id' => $cats['Ronds à béton'] ?? $cats['Fer & Acier'],
                'fournisseur_id'=> $sonasid,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'FER-TRE-001',
                'designation'  => 'Treillis soudé ST50 – 2.4×6 m',
                'description'  => 'Treillis soudé maille 15×15 cm, fil Ø 6 mm.',
                'prix_achat'   => 185.00,
                'prix_vente_ht'=> 235.00,
                'tva'          => 20,
                'unite'        => 'panneau',
                'stock_actuel' => 120,
                'stock_minimum'=> 20,
                'stock_maximum'=> 400,
                'categorie_id' => $cats['Treillis soudé'] ?? $cats['Fer & Acier'],
                'fournisseur_id'=> $sonasid,
                'statut'       => 'actif',
            ],

            // ── Carrelage ───────────────────────────────────────────────────
            [
                'reference'    => 'CAR-SOL-001',
                'designation'  => 'Carrelage grès émaillé 60×60 – Blanc Ivoire',
                'description'  => 'Carrelage sol rectifié, résistance PEI 4. Boîte de 4 pièces (1,44 m²).',
                'prix_achat'   => 88.00,
                'prix_vente_ht'=> 115.00,
                'tva'          => 20,
                'unite'        => 'm²',
                'stock_actuel' => 560,
                'stock_minimum'=> 100,
                'stock_maximum'=> 2000,
                'categorie_id' => $cats['Carrelage sol'] ?? $cats['Carrelage'],
                'fournisseur_id'=> $tileya,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'CAR-SOL-002',
                'designation'  => 'Carrelage grès cérame 80×80 – Gris Béton',
                'description'  => 'Carrelage grand format effet béton. Extérieur / intérieur.',
                'prix_achat'   => 155.00,
                'prix_vente_ht'=> 195.00,
                'tva'          => 20,
                'unite'        => 'm²',
                'stock_actuel' => 210,
                'stock_minimum'=> 50,
                'stock_maximum'=> 800,
                'categorie_id' => $cats['Carrelage sol'] ?? $cats['Carrelage'],
                'fournisseur_id'=> $tileya,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'CAR-MUR-001',
                'designation'  => 'Faïence murale 30×60 – Blanc Mat',
                'description'  => 'Faïence mural pour salle de bain et cuisine. Boîte 6 pièces.',
                'prix_achat'   => 62.00,
                'prix_vente_ht'=> 82.00,
                'tva'          => 20,
                'unite'        => 'm²',
                'stock_actuel' => 380,
                'stock_minimum'=> 80,
                'stock_maximum'=> 1200,
                'categorie_id' => $cats['Faïence'] ?? $cats['Carrelage mural'] ?? $cats['Carrelage'],
                'fournisseur_id'=> $tileya,
                'statut'       => 'actif',
            ],

            // ── Plomberie ───────────────────────────────────────────────────
            [
                'reference'    => 'PLO-PVC-032',
                'designation'  => 'Tube PVC pression Ø32 – 3 mètres',
                'description'  => 'Tube PVC PN16 pour alimentation eau potable.',
                'prix_achat'   => 22.00,
                'prix_vente_ht'=> 30.00,
                'tva'          => 20,
                'unite'        => 'barre',
                'stock_actuel' => 145,
                'stock_minimum'=> 30,
                'stock_maximum'=> 500,
                'categorie_id' => $cats['Tubes PVC'] ?? $cats['Plomberie'],
                'fournisseur_id'=> $plomberie,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'PLO-PVC-050',
                'designation'  => 'Tube PVC évacuation Ø50 – 3 mètres',
                'description'  => 'Tube PVC NF EU pour évacuation eaux usées.',
                'prix_achat'   => 34.00,
                'prix_vente_ht'=> 45.00,
                'tva'          => 20,
                'unite'        => 'barre',
                'stock_actuel' => 98,
                'stock_minimum'=> 20,
                'stock_maximum'=> 300,
                'categorie_id' => $cats['Tubes PVC'] ?? $cats['Plomberie'],
                'fournisseur_id'=> $plomberie,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'PLO-ROB-001',
                'designation'  => 'Robinet mélangeur cuisine chromé',
                'description'  => 'Mitigeur monocommande avec douchette extractible.',
                'prix_achat'   => 185.00,
                'prix_vente_ht'=> 245.00,
                'tva'          => 20,
                'unite'        => 'unité',
                'stock_actuel' => 42,
                'stock_minimum'=> 10,
                'stock_maximum'=> 100,
                'categorie_id' => $cats['Robinetterie'] ?? $cats['Plomberie'],
                'fournisseur_id'=> $plomberie,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'PLO-RAC-001',
                'designation'  => 'Coude PVC 90° Ø50',
                'description'  => 'Coude pour évacuation PVC. Joint intégré.',
                'prix_achat'   => 5.50,
                'prix_vente_ht'=> 8.00,
                'tva'          => 20,
                'unite'        => 'unité',
                'stock_actuel' => 8,
                'stock_minimum'=> 50,
                'stock_maximum'=> 500,
                'categorie_id' => $cats['Raccords'] ?? $cats['Plomberie'],
                'fournisseur_id'=> $plomberie,
                'statut'       => 'rupture',
            ],

            // ── Peinture ────────────────────────────────────────────────────
            [
                'reference'    => 'PNT-INT-001',
                'designation'  => 'Peinture intérieure acrylique blanche – Seau 20 L',
                'description'  => 'Peinture acrylique mate lavable. Couvrance 8–10 m²/L.',
                'prix_achat'   => 195.00,
                'prix_vente_ht'=> 255.00,
                'tva'          => 20,
                'unite'        => 'seau',
                'stock_actuel' => 85,
                'stock_minimum'=> 15,
                'stock_maximum'=> 200,
                'categorie_id' => $cats['Peinture intérieure'] ?? $cats['Peinture'],
                'fournisseur_id'=> $colorplus,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'PNT-EXT-001',
                'designation'  => 'Peinture façade hydrofuge – Seau 25 L',
                'description'  => 'Peinture extérieure résistante aux intempéries. Anti-mousse.',
                'prix_achat'   => 320.00,
                'prix_vente_ht'=> 420.00,
                'tva'          => 20,
                'unite'        => 'seau',
                'stock_actuel' => 62,
                'stock_minimum'=> 10,
                'stock_maximum'=> 150,
                'categorie_id' => $cats['Peinture extérieure'] ?? $cats['Peinture'],
                'fournisseur_id'=> $colorplus,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'PNT-END-001',
                'designation'  => 'Enduit de lissage – Sac 25 kg',
                'description'  => 'Enduit de finition intérieur en poudre. Séchage rapide.',
                'prix_achat'   => 65.00,
                'prix_vente_ht'=> 85.00,
                'tva'          => 20,
                'unite'        => 'sac',
                'stock_actuel' => 140,
                'stock_minimum'=> 30,
                'stock_maximum'=> 400,
                'categorie_id' => $cats['Enduits'] ?? $cats['Peinture'],
                'fournisseur_id'=> $colorplus,
                'statut'       => 'actif',
            ],

            // ── Bois & Menuiserie ───────────────────────────────────────────
            [
                'reference'    => 'BOI-CTP-001',
                'designation'  => 'Contreplaqué coffrage 18 mm – 1.22×2.44 m',
                'description'  => 'Contreplaqué pin pour coffrage béton. Usage multiple.',
                'prix_achat'   => 185.00,
                'prix_vente_ht'=> 240.00,
                'tva'          => 20,
                'unite'        => 'panneau',
                'stock_actuel' => 75,
                'stock_minimum'=> 15,
                'stock_maximum'=> 300,
                'categorie_id' => $cats['Contreplaqué'] ?? $cats['Bois & Menuiserie'],
                'fournisseur_id'=> $boisCo,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'BOI-PLN-001',
                'designation'  => 'Planche sapin 27 mm – 4 mètres',
                'description'  => 'Planche de charpente raboté 4 faces. Sec.',
                'prix_achat'   => 42.00,
                'prix_vente_ht'=> 55.00,
                'tva'          => 20,
                'unite'        => 'pièce',
                'stock_actuel' => 180,
                'stock_minimum'=> 30,
                'stock_maximum'=> 500,
                'categorie_id' => $cats['Planches'] ?? $cats['Bois & Menuiserie'],
                'fournisseur_id'=> $boisCo,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'BOI-POR-001',
                'designation'  => 'Porte isoplane 90×210 cm – Hêtre',
                'description'  => 'Porte intérieure isoplane avec chambranlé. Pré-percée.',
                'prix_achat'   => 480.00,
                'prix_vente_ht'=> 620.00,
                'tva'          => 20,
                'unite'        => 'unité',
                'stock_actuel' => 28,
                'stock_minimum'=> 5,
                'stock_maximum'=> 80,
                'categorie_id' => $cats['Portes'] ?? $cats['Bois & Menuiserie'],
                'fournisseur_id'=> $boisCo,
                'statut'       => 'actif',
            ],

            // ── Électricité ─────────────────────────────────────────────────
            [
                'reference'    => 'ELE-CAB-001',
                'designation'  => 'Câble R2V 2×1.5 mm² – Rouleau 100 m',
                'description'  => 'Câble souple pour circuit d\'éclairage. Norme NF.',
                'prix_achat'   => 245.00,
                'prix_vente_ht'=> 320.00,
                'tva'          => 20,
                'unite'        => 'rouleau',
                'stock_actuel' => 55,
                'stock_minimum'=> 10,
                'stock_maximum'=> 150,
                'categorie_id' => $cats['Câbles'] ?? $cats['Électricité'],
                'fournisseur_id'=> $electro,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'ELE-CAB-002',
                'designation'  => 'Câble R2V 3×2.5 mm² – Rouleau 100 m',
                'description'  => 'Câble pour prises de courant 16A. Norme NF.',
                'prix_achat'   => 385.00,
                'prix_vente_ht'=> 495.00,
                'tva'          => 20,
                'unite'        => 'rouleau',
                'stock_actuel' => 38,
                'stock_minimum'=> 8,
                'stock_maximum'=> 100,
                'categorie_id' => $cats['Câbles'] ?? $cats['Électricité'],
                'fournisseur_id'=> $electro,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'ELE-INT-001',
                'designation'  => 'Interrupteur va-et-vient Legrand – Blanc',
                'description'  => 'Interrupteur double allumage série Niloe.',
                'prix_achat'   => 18.00,
                'prix_vente_ht'=> 26.00,
                'tva'          => 20,
                'unite'        => 'unité',
                'stock_actuel' => 210,
                'stock_minimum'=> 50,
                'stock_maximum'=> 500,
                'categorie_id' => $cats['Interrupteurs'] ?? $cats['Électricité'],
                'fournisseur_id'=> $electro,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'ELE-PRI-001',
                'designation'  => 'Prise 2P+T 16A Legrand – Blanc',
                'description'  => 'Prise de courant avec terre, série Niloe.',
                'prix_achat'   => 22.00,
                'prix_vente_ht'=> 32.00,
                'tva'          => 20,
                'unite'        => 'unité',
                'stock_actuel' => 180,
                'stock_minimum'=> 50,
                'stock_maximum'=> 500,
                'categorie_id' => $cats['Prises'] ?? $cats['Électricité'],
                'fournisseur_id'=> $electro,
                'statut'       => 'actif',
            ],

            // ── Isolation ───────────────────────────────────────────────────
            [
                'reference'    => 'ISO-LDR-001',
                'designation'  => 'Laine de roche 100 mm – Rouleau 10 m²',
                'description'  => 'Laine de roche acoustique et thermique. Lambda 0.035.',
                'prix_achat'   => 195.00,
                'prix_vente_ht'=> 260.00,
                'tva'          => 20,
                'unite'        => 'rouleau',
                'stock_actuel' => 65,
                'stock_minimum'=> 15,
                'stock_maximum'=> 200,
                'categorie_id' => $cats['Laine de roche'] ?? $cats['Isolation'],
                'fournisseur_id'=> $iso,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'ISO-PSE-001',
                'designation'  => 'Polystyrène expansé 50 mm – Plaque 0.6×1.2 m',
                'description'  => 'Isolant thermique façade et toiture. Densité 20 kg/m³.',
                'prix_achat'   => 28.00,
                'prix_vente_ht'=> 38.00,
                'tva'          => 20,
                'unite'        => 'plaque',
                'stock_actuel' => 250,
                'stock_minimum'=> 50,
                'stock_maximum'=> 800,
                'categorie_id' => $cats['Polystyrène'] ?? $cats['Isolation'],
                'fournisseur_id'=> $iso,
                'statut'       => 'actif',
            ],
            [
                'reference'    => 'ISO-MEM-001',
                'designation'  => 'Membrane d\'étanchéité bitumineuse 4 mm – Rouleau 10 m²',
                'description'  => 'Membrane SBS autoprotégée pour toiture terrasse.',
                'prix_achat'   => 420.00,
                'prix_vente_ht'=> 560.00,
                'tva'          => 20,
                'unite'        => 'rouleau',
                'stock_actuel' => 35,
                'stock_minimum'=> 8,
                'stock_maximum'=> 100,
                'categorie_id' => $cats['Membrane étanche'] ?? $cats['Isolation'],
                'fournisseur_id'=> $iso,
                'statut'       => 'actif',
            ],
        ];

        foreach ($produits as $data) {
            Produit::firstOrCreate(['reference' => $data['reference']], $data);
        }

        $this->command->info('Produits créés : ' . count($produits));
    }
}
